#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/../@redocly/reference-docs/bin/cli/commands/redocly-docs-cli.min.js" "$@"
  ret=$?
else 
  node  "$basedir/../@redocly/reference-docs/bin/cli/commands/redocly-docs-cli.min.js" "$@"
  ret=$?
fi
exit $ret
