import 'core-js/es/array/find-index';
import 'core-js/es/array/find';
import 'core-js/es/array/includes';
import 'core-js/es/map';
import 'core-js/es/number/is-integer';
import 'core-js/es/object/assign';
import 'core-js/es/object/entries';
import 'core-js/es/object/is';
import 'core-js/es/object/values';
import 'core-js/es/promise';
import 'core-js/es/string/ends-with';
import 'core-js/es/string/starts-with';
import 'core-js/es/symbol';
import 'unfetch/polyfill/index';
import 'url-polyfill';
import { OpenAPIDefinition } from './redoc-lib';
import { ProStoreState, RedocProRawOptions } from './services/ProStore';
import { LayoutVariant } from './services/store-types';
import { SpecVersions } from './services/VersionedSpecStore';
export { setSecurityDetails, setParameterValue, setSecurityDetailsVariants } from './utils';
export declare function toggleLayout(layout?: LayoutVariant): void;
export declare function toggleRightPanel(value?: boolean): void;
export declare function hydrate(state: ProStoreState, element?: Element | null): void;
export declare function init(definitionOrDefinitionUrl: string | OpenAPIDefinition | SpecVersions, options?: RedocProRawOptions, element?: Element | null, callback?: () => void): void;
export declare function setPublicPath(path: string): void;
export declare const version: string;
export declare const revision: string;
